config/routes.rb
Rails.application.routes.draw do
  
  resources :profiles do
     resources :reviews, :except => [:show, :index] 
  end
  devise_for :users

  get '/profiles/:profile_id/reviews', to: redirect('/profiles/:profile_id')
  get '/profiles/:profile_id/reviews/:id', to: redirect('/profiles/:profile_id')
  get '/posts', to: redirect('/')
  

  get 'contact', to:'pages#contact'
  post 'contact_seller', to: 'posts#contact_seller'

  post 'request_contact', to: 'pages#request_contact'
  root 'posts#index'

  resources :posts

  

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	#profile belongs to a user
	belongs_to :user
	#can have many reviews, also dependent destroy so any reviews would be destroyed if profile was destroyed
	has_many :reviews, dependent: :destroy
	#Checks if the fields are present
	validates :user_id, :first_name, :last_name, :number, :address_one,
	:city, :postal_code, presence: true
	#Checks if the user id is unique
	validates :user_id, uniqueness: true
	#checks if phone number has a valid format
	validates :number, format: { with: /\d{11}/, message: "Enter valid phone number" }
	#checks if post code has a valid format
    validates :postal_code, format: { with: /([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9][A-Za-z]?))))\s?[0-9][A-Za-z]{2})/,
    message: "Enter valid post code" }

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  #Sets the profile
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  #Only users that have signed in can have access to these actions
  before_action :authenticate_user!, only: [:new, :edit, :destroy, :update, :create]
  #Prevents users from editing/destroying some one else's profile
  before_action :check, only: [:edit, :update, :destroy,]
  #The show action which used to show a user's profile. It shows a list of reviews and posts
  def show
    @reviews = Review.where(profile_id: params[:id])
    @reviews = @reviews.order(created_at: :desc)
    @posts = Post.where(:user_id => @profile.user_id).descending
    #If the reviews is blank..
    if @reviews.blank?
      #set average as 0
      @avg=0
    else
      #else if the reviews section is not blank
      @avg = @reviews.average(:rating).round(2)
    end
  end
  #The newaction is used allowing a user to create a profile
  def new
    @profile = current_user.build_profile
    @created = true
  end
  # The edit action is used allowing a user to edit a profile
  def edit
  end
  # The create action is used to allow a profile to be populated and saved to the database
  def create
    @profile = current_user.build_profile(profile_params)
    respond_to do |format|
      if @profile.save
        #Mails the user once they set up their profile
        #ContactMailer.register_email(current_user.email.to_s).deliver_now
        format.html { redirect_to @profile, notice: I18n.t('.success') }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end
  # The update action allows the user to add chantes to their profile
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: I18n.t('.success_update') }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end
  # The destroy action is used to destroy a user's profile
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: I18n.t('.success_destroy') }
      format.json { head :no_content }
    end
  end
  #private methods used within this file
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end


    #Checks to see if the current user is the creator of the profile before the editing/updating/deleting/ actions
    def check
      if user_signed_in?
        unless current_user.id == @profile.user_id
          flash[:notice] = I18n.t('posts.edit.alertno')
          redirect_to root_path
         return
        end
      end
      #Gets redirected back to the root path
    end
    # Using strong parameter to only allow the following parameters
    def profile_params
        params.require(:profile).permit(
          :first_name,
          :last_name,
          :number,
          :city,
          :address_one,
          :address_two,
          :address_three,
          :postal_code)
    end

end

app/helpers/profiles_helper.rb
module ProfilesHelper

end

app/views/profiles/_form.html.haml
-# Allows a profile to be created/ edited
= simple_form_for(@profile) do |f|
	= f.input :first_name ,label: false, placeholder: t('.first_name')
	= f.input :last_name ,label: false, placeholder:  t('.last_name')
	%h4= t('additional')
	= f.input :number,label: false, placeholder: t('posts.form.number')
	= f.input :city,label: false, placeholder: t('posts.form.city')
	= f.input :address_one,label: false, placeholder: t('posts.form.address_one')
	= f.input :address_two,label: false, placeholder: t('posts.form.address_two')
	= f.input :address_three,label: false, placeholder: t('posts.form.address_three')
	= f.input :postal_code,label: false, placeholder: t('posts.form.postal_code')
	= f.button :submit, t('.button')

app/views/profiles/_review.html.haml
-# Goes through each review and generates a nice looking list of reviews
- @reviews.each do |review| 
	%hr
	%h5
		%strong= link_to review.user.profile.first_name, review.user.profile
		wrote
		%small
			= time_ago_in_words(review.created_at) 
			ago
		- if user_signed_in?
			- if review.user_id==current_user.id
				.button-group.pull-right
					= link_to 'Edit', edit_profile_review_path(review.profile, review), class: "btn btn-default"
					= link_to 'Delete', profile_review_path(review.profile, review), method: :delete, data: { confirm: 'Are you sure!?'}, class: "btn btn-default"

	.review-rating{"data-score": review.rating} 
	%h5=review.comment

app/views/profiles/edit.html.haml
.container#wrapped
	#profile_edit.row
		.col-md-8.col-md-offset-2
			.panel.panel-default
				.panel-body
					-#Content body, renders an edit form
					%h1= t('.title')
					=render 'form'
				.panel-footer
					-#Footer
					.row
						.col-md-12
							.btn-group.pull-right
								= link_to t('back'), root_path, class: "btn btn-default"

app/views/profiles/new.html.haml
.container#wrapped
	#profile_new.row
		.col-md-8.col-md-offset-2
			.panel.panel-default
				.panel-body
					%h1= t('.title')
					=render 'form'
				.panel-footer
					.row
						.col-md-12
							.btn-group.pull-right
								= link_to t('back'), root_path, class: "btn btn-default"

app/views/profiles/show.html.haml
.container#wrapped
	#profile_show.row
		.col-md-8.col-md-offset-2
			.panel.panel-default
				.panel-body
					-#Content body displaying user profiled details
					- if user_signed_in? && @profile.user_id == current_user.id
						%h1= t('.myprofile')
					- else 
						%h1= @profile.first_name + ' ' + @profile.last_name + ' Profile'
					%hr.divider
					.avg-rating{'data-score' => @avg}
					%p
						%small
							= t('.based')
							=@reviews.count
							= t('.reviews')

					%p= @profile.user.email
					%p= @profile.number
					-# has the user logged in and set up a profile?
					-# is it their own profile?
					-# If so display a their contact details
					%p= @profile.city
					%p= @profile.address_one
					%p= @profile.address_two 
					%p= @profile.address_three
					%p= @profile.postal_code
					- if user_signed_in? && @profile.user_id != current_user.id
						.btn-group#right.pull-left
							= link_to t('.addreview'), new_profile_review_path(@profile), class: "btn btn-default", id: 'review-btn'
					%br
					%br
					-#Renders a list of reviews
					=render 'review'
					-#A footer displaying buttons
				.panel-footer
					.row
						.col-md-12
							- if user_signed_in? && @profile.user_id == current_user.id
								.btn-group.pull-right
									= link_to t('.edit'), edit_profile_path(@profile), class: "btn btn-default"
									= link_to t('.back'), root_path, class: "btn btn-default"
							- else
								.btn-group.pull-right
									= link_to t('.back'), root_path, class: "btn btn-default"

-# Renders all the posts that the user has submitted
.halfpage
	= render 'shared/posts'

-# Provies some java script so that stars will appear instead of a solid number
-# Adds to user experience
:javascript
	$('.review-rating').raty({
		path: '/assets',
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});

:javascript
	$('.avg-rating').raty({
		path: '/assets',
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});