config/routes.rb
Rails.application.routes.draw do
  
  resources :profiles do
     resources :reviews, :except => [:show, :index] 
  end
  devise_for :users

  get '/profiles/:profile_id/reviews', to: redirect('/profiles/:profile_id')
  get '/profiles/:profile_id/reviews/:id', to: redirect('/profiles/:profile_id')
  get '/posts', to: redirect('/')
  

  get 'contact', to:'pages#contact'
  post 'contact_seller', to: 'posts#contact_seller'

  post 'request_contact', to: 'pages#request_contact'
  root 'posts#index'

  resources :posts

  

end

app/views/shared/_footer.html.haml
%footer
	.wrapper
		%nav
			%ul
				-# Adds links to the footer to redirect the user if needed
				%li= link_to 'Home', root_path
				%li= link_to t('shared.header.contact'), contact_path
				- if user_signed_in?
					- if current_user.profile==nil
						%li= link_to t('shared.header.createprofile'), new_profile_path
					- elsif current_user.profile.new_record?
						%li= link_to t('shared.header.createprofile'), new_profile_path
					- elsif current_user.profile.persisted?
						%li= link_to t('shared.header.post'), new_post_path
						%li= link_to t('shared.header.myprofile'), current_user.profile
						%li= link_to t('shared.header.signout'), destroy_user_session_path, method: :delete
				- else
					%li= link_to t('shared.header.register'), new_user_registration_path
					%li= link_to t('shared.header.signin'), new_user_session_path

app/views/shared/_header.html.haml
%nav.navbar.navbar-default.navbar-static-top{:role => "navigation"}
  .container-fluid
    -# Brand and toggle get grouped for better mobile display
    .navbar-header
      %button#toggle.navbar-toggle{"data-target" => "#navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to image_tag('/assets/EarthLogo.png'), root_path,class: 'navbar-brand'
      = link_to t('app_title'), root_path, class: 'navbar-brand'
    -# Collect the nav links, forms, and other content for toggling
    #navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        -#Links that is in my navbar
        %li= link_to t('.contact'), contact_path
        - if user_signed_in?
          - if current_user.profile==nil
            %li= link_to t('.createprofile'), new_profile_path
          - elsif current_user.profile.new_record?
            %li= link_to t('.createprofile'), new_profile_path
          - elsif current_user.profile.persisted?
            %li= link_to t('.post'), new_post_path
            %li= link_to t('.myprofile'), current_user.profile
          %li= link_to t('.signout'), destroy_user_session_path, method: :delete
        - else
          %li= link_to t('.register'), new_user_registration_path
          %li= link_to t('.signin'), new_user_session_path
-#alerts and notices
.container#flash
  -flash.each do |name,msg|
    = content_tag :div, msg, class:"alert alert-info"

app/views/shared/_posts.html.haml
-# Provides a masonry layout when displaying the list of posts
.container
	.masonry
		- @posts.each do |post|
			.card
				%a{:href => "/posts/#{post.id}"}
					= image_tag post.post_image.url(:post_index), class: "post"
					.description
						%h4= post.title
						%p= post.price