config/routes.rb
Rails.application.routes.draw do
  
  resources :profiles do
     resources :reviews, :except => [:show, :index] 
  end
  devise_for :users

  get '/profiles/:profile_id/reviews', to: redirect('/profiles/:profile_id')
  get '/profiles/:profile_id/reviews/:id', to: redirect('/profiles/:profile_id')
  get '/posts', to: redirect('/')
  

  get 'contact', to:'pages#contact'
  post 'contact_seller', to: 'posts#contact_seller'

  post 'request_contact', to: 'pages#request_contact'
  root 'posts#index'

  resources :posts

  

end

app/models/post.rb
class Post < ActiveRecord::Base
	#Post belongs to a user and category
	belongs_to :user
	belongs_to :category
	#descending scope is defined to be used in the post controller
	scope :descending, -> {order(created_at: :desc)}
	#Validates the fields and checks if they are empty
    validates :title, :description, :price, :address_one, :city, :postal_code,
    :city, :postal_code, :phone_number, :category_id, :user_id, presence: true 
    #Validates the phone number checking if it has a valid phone number
	validates :phone_number, format: { with: /\d{11}/}
	#Validates the postal code checking if it has a valida email
    validates :postal_code, format: { with: /([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9][A-Za-z]?))))\s?[0-9][A-Za-z]{2})/}
    #Sets up paper clip to be used within post
	has_attached_file :post_image, styles: { post_index: "300x300>", post_show: "300x300>" }, default_url: "/images/:style/missing.png"
	#validates an image, 
 	validates_attachment_content_type :post_image, content_type: /\Aimage\/.*\z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	#runs the find_post method before the selected methods
	before_action :find_post, only: [:show, :edit, :update, :destroy, :request_contact]
	before_action :authenticate_user!, only: [:edit, :destroy, :update, :new, :create, :request_contact]
	before_action :must_make_account, only: [:new, :create, :contact_seller]
	before_action :check, only: [:edit, :update, :destroy,]
	#Represents the index action
	#This will list all the posts depending on the selected category/query
	def index
		if params[:category].blank?
			@posts = Post.all.descending
		else
			@category_id = Category.find_by(name: params[:category]).id
			@posts = Post.where(:category_id => @category_id).descending
			# Splits the array into further arrays which would represent rows, the rows will then 
			# be displayed on the index page
		end
	end

	#Represents the show action, allows the user to view a particular post
	def show
		#no need to redirect user here
	end

	#Represents the edit action, allows the creator to edit their psot
	def edit
	end

	#Represents the destroy action, only allows the creator to destroy their post
	def destroy
		if @post.destroy
			flash[:notice] = I18n.t('.success')
			redirect_to root_path
		else 
			flash[:notice] = I18n.t('.fail')
			render :show
		end
	end

	#Represents the Update aciton, only allows the creator to update their post
	def update
		#If the update doesnt include the category then do not try to update the category
		unless (post_params[:category_id]==nil)
			#else update it if the category parameter is not null...
			@post.category = Category.find(post_params[:category_id].to_i)
		end
		#Now update the post
		if @post.update(post_params) 
			#Redirect to the updated post (show)
			redirect_to post_path(@post)
		else
			render :edit
		end
	end

	#Represents the new action, only allows users with a profile to create a new post
	def new
		#Defines an instance of a model which can be used in our view
		#@post = Post.new
		@post = current_user.posts.build
		#Gets all the catogories
	end

	#Represents the create action, only allows users with a set up profile to create a new post
	def create
		#@post = Post.new(post_params)
		@post =current_user.posts.build(post_params)
		@post.category = Category.find(post_params[:category_id].to_i)
		if @post.save
			#If the post saved succesfully then redirect to root path (index)
			redirect_to root_path
		else
			#else redirect to /posts/new route
			render :new
		end
	end

	#This feature failed to work, to reduce time waste it'll be removed and a contact page
	#will be added instead
	#The request_contact action allows the user to send an email to the seller/post-creator
	def contact_seller
		mail_user_name = params[:mail][:user_name] #User object
		mail_user_email = params[:mail][:user_email] #User object
		mail_user_telephone = params[:mail][:user_telephone] #User object
		mail_seller_email = params[:mail][:seller_user_email]#Seller user object
		mail_post_title = params[:mail][:post_title] #currently viewed post object
		mail_message = params[:mail][:message] #the message
		#If the messages are blank then dont sent the mail
		# Else send the email!
		if mail_message.blank?
			flash[:alert] = I18n.t('posts.request_contact.no_message')
		else
			#sending email
			ContactMailer.contact_email(mail_user_name, mail_user_email, mail_user_telephone,mail_seller_email ,mail_post_title, mail_message).deliver_now
			flash[:notice] = I18n.t('posts.request_contact.email_sent')
		end

		# Redirect to root path (ie home page)
		redirect_to root_path
	end



	private
		#Strong parameter!
		#populates the instance of a new post model from the form
		def post_params	
				params.require(:post).permit(
					:post_image,
					:title,
					:description,
					:price,
					:phone_number,
					:city,
					:address_one,
					:address_two,
					:address_three,
					:postal_code,
					:category_id)
		end

		#Checks to see if the current user has set up a profile before the editing/creating/updating/deleting/contacting actions
		def must_make_account
			#Checks if profile is nil, ie hasnt been set up
			if user_signed_in?
				if current_user.profile==nil
    		 		flash[:notice] = I18n.t('posts.edit.alertnew')
     		 		redirect_to new_profile_path
      				return
      			end
      		end
      		#Gets redirected back to the post show page
      	end

      	#Checks to see if the current user is the creator of the post before the editing/updating/deleting/ actions
      	def check
      		if user_signed_in?
	      		unless current_user.id == @post.user_id
	    		 flash[:notice] = I18n.t('posts.edit.alertno')
	     		 redirect_to post_path(@post)
	      		 return
	      		end
	      	end
      		#Gets redirected back to the post show page
      	end
		
      	#Finds the post with the parameter id passed in
      	# Also finds the user who is associated with the post
		def find_post
			@post = Post.find(params[:id])
			@seller = User.find(@post.user.id)
		end
	

end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/posts/_contact.html.haml
-# Takes in the users messages
-# Hidden parameters such as the user/post/seller object are also taken in
-# They'll be used to generate an email which will be sent to the seller
= simple_form_for :mail, {url: contact_seller_path} do |f|
	= f.input :message,label: false, placeholder: t('.title')
	= f.input :user_name, :as => :hidden, :input_html => { :value => current_user.profile.first_name+current_user.profile.last_name}
	= f.input :user_email, :as => :hidden, :input_html => { :value => current_user.email}
	= f.input :user_telephone, :as => :hidden, :input_html => { :value => current_user.profile.number}
	= f.input :seller_user_email, :as => :hidden, :input_html => { :value => @seller.email}
	= f.input :post_title, :as => :hidden, :input_html => { :value => @post.title }
	= f.button :submit, t('.submit')
	-# disabled: true, readonly: true

app/views/posts/_form.html.haml
-#Form which allows a user to create a post
= simple_form_for @post, :html => { :multipart => true } do |f|
	.form-group
		= f.input :post_image, input_html: {class: 'form-control'}, label: false
	= f.input :title,label: false, placeholder: t('.title')
	= f.input :description,label: false, placeholder: t('.description')
	.form-group#category
		= f.select :category_id, options_from_collection_for_select(Category.all, :id, :name), input_html: {class: "form-control"}
	= f.input :price,label: false, placeholder: t('.price')
	%h4= t('.contact')
	-# Displays the user's address from profile, only if the user is creating a new post, not editing
	- if current_page?(controller: :posts, action: :new)
		= f.input :phone_number,label: false, placeholder: t('.number'), input_html: {value: current_user.profile.number}
		= f.input :city,label: false, placeholder: t('.city'),  input_html: {value: current_user.profile.city}
		= f.input :address_one,label: false, placeholder: t('.address_one'),input_html: {value: current_user.profile.address_one}
		= f.input :address_two,label: false, placeholder: t('.address_two'), input_html: {value: current_user.profile.address_two}
		= f.input :address_three,label: false, placeholder: t('.address_three'), input_html: {value: current_user.profile.address_three}
		= f.input :postal_code,label: false, placeholder: t('.postal_code'), input_html: {value: current_user.profile.postal_code }
		= f.button :submit, t('.submit') 
	- else
		-# Displays the posts already existing address
		= f.input :phone_number,label: false, placeholder: t('.number')
		= f.input :city,label: false, placeholder: t('.city')
		= f.input :address_one,label: false, placeholder: t('.address_one')
		= f.input :address_two,label: false, placeholder: t('.address_two')
		= f.input :address_three,label: false, placeholder: t('.address_three')
		= f.input :postal_code,label: false, placeholder: t('.postal_code')
		= f.button :submit, t('.editsubmit') 

app/views/posts/_masthead.haml
%header.masthead{style: "background-image: url('assets/sample.jpg')"}
	-# Used to add effect to the masthead image
	.overlay
	.container
		.row
			.col-lg-12.mx-auto
				-# HEADING
				.site-heading
					%h1= t('app_title_space')
					-#SEARCH FIELD
					.container
						.row
							.col-xs-8.col-xs-offset-2
								.input-group
									.input-group-btn.search-panel
										%button#menu.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
											%span#search_concept Categories
											%span.caret
										%ul.dropdown-menu{:role => "menu"}
											- Category.all.each do |category|
												%li{:class => "#{'selected' if params[:category] == category.name}"}
													=link_to category.name, posts_path(category: category.name), class: 'link'
											%li.divider
											%li
												%a{:href => "/"} All
									-#SEARCH BUTTON
									%input#search_param{:name => "search_param", :type => "hidden", :value => "all"}
										%input.form-control{:name => "x", :placeholder => "Search for something", :type => "text"}
											%span.input-group-btn
												%button.btn.btn-default{:type => "button"}
													Search
					-#SUBHEADING
					%br
					%span.subheading Find something in time for christmas

-#= simple_form_for :search, {url: posts_path} do |f|
-#	= f.input :user_email, :as => :hidden, :input_html => { :value => current_user.email}
-#	= f.input :user_telephone, :as => :hidden, :input_html => { :value => current_user.profile.number}

app/views/posts/edit.html.haml
.container#wrapped
	#post_edit.row
		.col-md-8.col-md-offset-2
			.panel.panel-default
				-#Holds the image
				.panel-heading.post_image
					= image_tag @post.post_image.url(:post_show), class: "image_show"
				-#Content
				.panel-body
					-#Renders the edit post page
					%h3= t('.title')
					=render 'form'
				-#footer
				.panel-footer
					.row
						.col-md-12
							.btn-group.pull-right
								= link_to t('.back'), root_path, class: "btn btn-default"


	

app/views/posts/index.html.haml
-# masthead containing an image that covers the width of a page
-# Has a title, subehading and a search bar taken from: 
-# https://bootsnipp.com/snippets/featured/search-panel-with-filters
-#Renders a container with an image and search bar + text
= render 'masthead'

.container
	-#Displays the name of the selected category
	%h2.category
		%span.categories
			- if (params[:category]==nil) 
				=t('.recent')
			- else
				= params[:category]
			- if @posts.count == 0
				%p= t('.no_post')
		%hr

	-#Displays all posts in descending order of creation
	= render 'shared/posts'

	%hr 
		.intro
			#wrap.wrapper
				%h3= t('.myproject')
				%p= t('.myappdescription')

app/views/posts/new.html.haml
.container#wrapped
	#post_show.row
		.col-md-8.col-md-offset-2
			.panel.panel-default
				-#Content
				.panel-body
					-#Renders form to create a new post
					%h3= t('.title')
					=render 'form'
				-#Footer
				.panel-footer
					.row
						.col-md-12
							.btn-group.pull-right
								= link_to t('.back'), root_path, class: "btn btn-default"

app/views/posts/show.html.haml
.container#wrapped
	#post_show.row
		.col-md-8.col-md-offset-2
			.panel.panel-default
				.panel-heading.post_image
					-#Header which holds an image
					= image_tag @post.post_image.url(:post_show), class: 'image_show'
				.panel-body
					-#Content body displaying the post details
					%h1= @post.title
					%p
						= @post.category.name + ' | ' if @post.category 
						= t('.creator')
						= link_to @post.user.profile.first_name+' '+ @post.user.profile.last_name, @post.user.profile
						= link_to " | "+@post.user.email, @post.user.profile
					%p= @post.description
					-# has the user logged in and set up a profile?
					-# If so display a contact button
					-# if user_signed_in?
					- if user_signed_in?
						- unless current_user.profile==nil
							- if current_user.profile.persisted? &&  @post.user_id!=current_user.id
								= render "contact"
					-#Footer which adds functionality (buttons)
				.panel-footer
					.row
						.col-md-12
							- if user_signed_in? && @post.user_id == current_user.id
								.btn-group.pull-right
									= link_to t('.edit'), edit_post_path(@post), class: "btn btn-default"
									= link_to t('.delete'), post_path(@post), method: :delete, data: { confirm: t('.confirmation')}, class: "btn btn-default"
									= link_to t('.back'), posts_path, class: "btn btn-default"
							- else
								.btn-group.pull-right
									= link_to t('.back'), posts_path, class: "btn btn-default"
									